version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - local.env
    command: uvicorn main:application_server --host 0.0.0.0 --port 8000 --reload
